import{transposeBody,transposeChord,extractChords,normalizeKnown,bestTranspositions}from'./chord-engine.js';import{parseSong}from'./parser.js';import{chordDiagramSvg,chordShape}from'./diagrams.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const STORE='guitar-songbook-v1';const DEFAULT='C D E G A Am Dm Em A7 D7 E7 G7 Cmaj7 Fmaj7 Asus2 Asus4 Dsus2 Dsus4';let state=JSON.parse(localStorage.getItem(STORE)||'{"songs":[],"known":""}');if(!state.known)state.known=DEFAULT;let current=null,shift=0,scrollTimer=null,speed=3,activeArtist='';const SCROLL_DELAYS={[-2]:260,[-1]:180,0:130,1:90,2:72,3:54,4:42,5:32,6:24};
function save(){localStorage.setItem(STORE,JSON.stringify(state))}function toast(t){const e=$('#toast');e.textContent=t;e.hidden=false;setTimeout(()=>e.hidden=true,2200)}
function nav(name){if(name==='import'){$('#importText').value='';$('#importSource').value=''}$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));window.scrollTo(0,0)}$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));
function artistGroups(){const groups=new Map;state.songs.forEach(s=>{const name=(s.artist||'Без исполнителя').trim(),key=name.toLocaleLowerCase('ru');if(!groups.has(key))groups.set(key,{name,count:0});groups.get(key).count++});return[...groups.values()].sort((a,b)=>a.name.localeCompare(b.name,'ru'))}
function renderArtists(){const groups=artistGroups();$('#artistSidebar').hidden=!state.songs.length;$('#artistList').innerHTML=`<button class="artist-link ${activeArtist?'':'active'}" data-artist=""><span>Все песни</span><b>${state.songs.length}</b></button>`+groups.map(g=>`<button class="artist-link ${activeArtist===g.name.toLocaleLowerCase('ru')?'active':''}" data-artist="${esc(g.name.toLocaleLowerCase('ru'))}"><span>${esc(g.name)}</span><b>${g.count}</b></button>`).join('');$$('.artist-link').forEach(b=>b.onclick=()=>{activeArtist=b.dataset.artist;renderList()})}
function renderList(){const q=$('#search').value.toLowerCase();const songs=state.songs.filter(s=>(!activeArtist||(s.artist||'Без исполнителя').trim().toLocaleLowerCase('ru')===activeArtist)&&(s.title+' '+s.artist).toLowerCase().includes(q)).sort((a,b)=>a.title.localeCompare(b.title,'ru'));$('#songList').innerHTML=songs.map(s=>`<article class="song-item" data-id="${s.id}"><h2>${esc(s.title)}</h2><p>${esc(s.artist||'Исполнитель не указан')}</p><div class="chips">${s.key?`<span class="chip">${esc(s.key)}</span>`:''}${s.capo?`<span class="chip">Капо ${s.capo}</span>`:''}<span class="chip">${extractChords(s.body).length} аккордов</span></div></article>`).join('');$('#emptyState').hidden=state.songs.length>0;$('#noResults').hidden=!state.songs.length||songs.length>0;const group=artistGroups().find(g=>g.name.toLocaleLowerCase('ru')===activeArtist);$('#songCount').textContent=activeArtist?`${songs.length} ${plural(songs.length,'песня','песни','песен')} · ${group?.name||''}`:`${state.songs.length} ${plural(state.songs.length,'песня','песни','песен')} · хранится на этом устройстве`;renderArtists();$$('.song-item').forEach(x=>x.onclick=()=>openSong(x.dataset.id))}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function plural(n,a,b,c){return n%10===1&&n%100!==11?a:n%10>=2&&n%10<=4&&(n%100<10||n%100>=20)?b:c}
function editor(song={title:'',artist:'',key:'',capo:0,bpm:0,strumming:'',source:'',body:''}){current=song.id||null;$('#editorTitle').textContent=current?'Редактировать песню':'Новая песня';$('#songTitle').value=song.title;$('#songArtist').value=song.artist;$('#songKey').value=song.key;$('#songCapo').value=song.capo||0;$('#songBpm').value=song.bpm||'';$('#songStrumming').value=song.strumming||'';$('#songSource').value=song.source||'';$('#songBody').value=song.body;$('#deleteSong').hidden=!current;$('#editorDialog').showModal()}
$('#newSong').onclick=()=>editor();$('#closeEditor').onclick=$('#cancelEditor').onclick=()=>$('#editorDialog').close();$('#parseButton').onclick=()=>{const raw=$('#importText').value;if(!raw.trim())return toast('Сначала вставьте текст');editor(parseSong(raw,$('#importSource').value.trim()))};$('#pasteButton').onclick=async()=>{const field=$('#importText');field.focus();try{if(!navigator.clipboard?.readText)throw 0;const value=await navigator.clipboard.readText();if(!value)throw 0;field.value=value;toast('Текст вставлен')}catch{toast('Safari не разрешил чтение буфера. Коснитесь поля и выберите «Вставить».')}};
$('#saveSong').onclick=()=>{const title=$('#songTitle').value.trim();if(!title)return toast('Укажите название');const song={id:current||crypto.randomUUID(),title,artist:$('#songArtist').value.trim(),key:$('#songKey').value.trim(),capo:+$('#songCapo').value||0,bpm:+$('#songBpm').value||0,strumming:$('#songStrumming').value.trim(),source:$('#songSource').value.trim(),body:$('#songBody').value.trim(),updatedAt:new Date().toISOString()};const i=state.songs.findIndex(s=>s.id===song.id);i>=0?state.songs[i]=song:state.songs.push(song);save();renderList();$('#editorDialog').close();nav('library');toast('Песня сохранена')};
$('#deleteSong').onclick=()=>{if(confirm('Удалить эту песню?')){state.songs=state.songs.filter(s=>s.id!==current);save();renderList();$('#editorDialog').close();toast('Песня удалена')}};
function markup(body){return esc(body).replace(/\[([A-G][^\]]*)\]/g,'<span class="chord">[$1]</span>').split('\n').map(line=>{const plain=line.replace(/<[^>]*>/g,''),ws=plain.trim().split(/\s+/);const chordLine=ws.length&&ws.filter(x=>/^[A-G][#b]?/.test(x)).length/ws.length>=.6;const content=chordLine?line.replace(/\b([A-G][#b]?(?:m|min|maj|M)?(?:\d{0,2})?(?:sus[24]?|dim\d*|aug\d*|add\d+)?(?:\/[A-G][#b]?)?)\b/g,'<span class="chord">$1</span>'):line;return`<span class="song-line ${chordLine?'chord-line':'lyric-line'}">${content||' '}</span>`}).join('')}
function openSong(id){current=id;shift=0;renderSong();$('#songDialog').showModal()}function renderSong(){const s=state.songs.find(x=>x.id===current);if(!s)return;const body=transposeBody(s.body,shift);$('#viewTitle').textContent=s.title;$('#viewArtist').textContent=[s.artist,s.bpm&&`${s.bpm} BPM`].filter(Boolean).join(' · ');$('#currentKey').textContent=s.key?transposeChord(s.key,shift):shift?(shift>0?`+${shift}`:shift):'—';$('#songContent').innerHTML=markup(body);$('#openSource').hidden=!s.source;$('#simpleAdvice').hidden=true}
$('#openSource').onclick=()=>{const s=state.songs.find(x=>x.id===current);if(s?.source)window.open(s.source,'_blank','noopener')};
$$('[data-shift]').forEach(b=>b.onclick=()=>{shift+=+b.dataset.shift;renderSong()});$('#closeSong').onclick=()=>$('#songDialog').close();$('#editSong').onclick=()=>{const s=state.songs.find(x=>x.id===current);$('#songDialog').close();editor(s)};
$('#simpleMode').onclick=()=>{const s=state.songs.find(x=>x.id===current),known=normalizeKnown(state.known),best=bestTranspositions(s.body,known).slice(0,3);const box=$('#simpleAdvice');box.hidden=false;box.innerHTML='<strong>Самые простые варианты:</strong> '+best.map(x=>`<button class="secondary suggestion" data-best="${x.shift}">${x.shift===0?'исходная':x.shift>0?'+'+x.shift:x.shift} · незнакомых: ${x.unknown.length}</button>`).join(' ');$$('.suggestion').forEach(b=>b.onclick=()=>{shift=+b.dataset.best;renderSong()})};
function chordPro(s){let body=s.body.split('\n');for(let i=0;i<body.length-1;i++){const chords=body[i].trim().split(/\s+/);if(chords.length&&chords.every(c=>/^[A-G][#b]?/.test(c))){const lyric=body[i+1];let out=lyric;let offset=0;let pos=0;for(const c of chords){const at=body[i].indexOf(c,pos);const insert=Math.min(at+offset,out.length);out=out.slice(0,insert)+`[${c}]`+out.slice(insert);offset+=c.length+2;pos=at+c.length}body.splice(i,2,out)}}return `{title: ${s.title}}\n{artist: ${s.artist||''}}\n${s.key?`{key: ${s.key}}\n`:''}${s.capo?`{capo: ${s.capo}}\n`:''}${s.bpm?`{tempo: ${s.bpm}}\n`:''}${s.strumming?`{comment: Бой: ${s.strumming}}\n`:''}\n${body.join('\n')}`}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}$('#exportChordPro').onclick=()=>{const s=state.songs.find(x=>x.id===current);download(`${s.title}.cho`,chordPro(s),'text/plain')};
$('#knownChords').value=state.known;$('#saveSettings').onclick=()=>{state.known=$('#knownChords').value.trim();save();toast('Настройки сохранены')};$('#exportJson').onclick=()=>download(`guitar-songbook-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2),'application/json');$('#importJson').onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.songs))throw 0;if(confirm(`Импортировать ${x.songs.length} песен? Текущая библиотека будет заменена.`)){state=x;save();renderList();$('#knownChords').value=state.known||DEFAULT;toast('Библиотека импортирована')}}catch{toast('Не удалось прочитать файл')}};$('#search').oninput=renderList;
function renderPlayDiagrams(){const s=state.songs.find(x=>x.id===current),chords=extractChords(transposeBody(s.body,shift)).filter(chordShape);$('#chordDiagrams').innerHTML=chords.map(c=>`<div class="diagram">${chordDiagramSvg(c)}</div>`).join('')||'<p>Схемы не найдены.</p>'}
function setDiagrams(on){if(on&&matchMedia('(orientation: portrait)').matches){$('#showDiagrams').checked=false;return toast('Аппликатуры появятся после поворота iPad горизонтально.')}$('#chordPanel').hidden=!on;$('#showDiagrams').checked=on}
$('#closeDiagrams').onclick=()=>setDiagrams(false);$('#showDiagrams').onchange=e=>setDiagrams(e.target.checked);addEventListener('orientationchange',()=>setTimeout(()=>{if(matchMedia('(orientation: portrait)').matches)setDiagrams(false)},200));
function closePanels(){$$('.play-popover').forEach(p=>p.hidden=true)}function openPanel(id){const was=$('#'+id).hidden;closePanels();$('#'+id).hidden=!was}$('#openPlaySettings').onclick=()=>openPanel('playSettings');$('#openTextSettings').onclick=()=>openPanel('textSettings');$('#toggleMetronome').onclick=()=>openPanel('metronomePanel');$$('[data-close-panel]').forEach(b=>b.onclick=closePanels);
$('#showLyrics').onchange=e=>$('#playContent').classList.toggle('hide-lyrics',!e.target.checked);$('#showChords').onchange=e=>$('#playContent').classList.toggle('hide-chords',!e.target.checked);$('#textSize').oninput=e=>{$('#playContent').style.fontSize=e.target.value+'px';$('#textSizeValue').value=e.target.value};$('#lineSpacing').oninput=e=>{const v=(e.target.value/10).toFixed(1);$('#playContent').style.lineHeight=v;$('#lineSpacingValue').value=v};$('#textColumns').onchange=e=>$('#playContent').style.columnCount=e.target.value;
let metroTimer=null,audioCtx=null;function metroClick(){audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=1000;g.gain.setValueAtTime(.18,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.06);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.07)}function stopMetronome(){clearInterval(metroTimer);metroTimer=null;$('#metronomeStart').textContent='▶ Запустить';$('#toggleMetronome').classList.remove('active')}function toggleMetro(){if(metroTimer)return stopMetronome();metroClick();metroTimer=setInterval(metroClick,60000/+$('#bpm').value);$('#metronomeStart').textContent='Ⅱ Остановить';$('#toggleMetronome').classList.add('active')}$('#metronomeStart').onclick=toggleMetro;$('#bpm').oninput=e=>{$('#bpmValue').value=e.target.value;if(metroTimer){stopMetronome();toggleMetro()}};
$('#playSong').onclick=()=>{const s=state.songs.find(x=>x.id===current);$('#playTitle').textContent=s.title;$('#playMeta').textContent=[s.artist,s.key&&transposeChord(s.key,shift),s.capo&&`капо ${s.capo}`,s.bpm&&`${s.bpm} BPM`].filter(Boolean).join(' · ');$('#playContent').innerHTML=markup(transposeBody(s.body,shift));$('#rhythmCard').hidden=!(s.bpm||s.strumming);$('#rhythmBpm').textContent=s.bpm?`${s.bpm} BPM`:'';$('#rhythmPattern').textContent=s.strumming||'';if(s.bpm){$('#bpm').value=s.bpm;$('#bpmValue').value=s.bpm}renderPlayDiagrams();setDiagrams(false);closePanels();$('#playMode').hidden=false;$('#songDialog').close();document.body.style.overflow='hidden'};function stopScroll(){clearInterval(scrollTimer);scrollTimer=null;$('#toggleScroll').textContent='▶';$('#toggleScroll').classList.remove('active')}function toggleScroll(){if(scrollTimer)return stopScroll();scrollTimer=setInterval(()=>$('#playMode').scrollBy({top:1,behavior:'auto'}),SCROLL_DELAYS[speed]);$('#toggleScroll').textContent='Ⅱ';$('#toggleScroll').classList.add('active')}$('#toggleScroll').onclick=toggleScroll;$('#exitPlay').onclick=()=>{stopScroll();stopMetronome();closePanels();$('#playMode').hidden=true;document.body.style.overflow='';$('#songDialog').showModal()};function speedName(){return speed===-2?'¼':speed===-1?'½':speed===0?'¾':speed}function setSpeed(n){speed=Math.max(-2,Math.min(6,n));$('#speedLabel').textContent=`Скорость ${speedName()}`;if(scrollTimer){stopScroll();toggleScroll()}}$('#slower').onclick=()=>setSpeed(speed-1);$('#faster').onclick=()=>setSpeed(speed+1);document.addEventListener('keydown',e=>{if($('#playMode').hidden)return;if(e.key==='ArrowRight'){e.preventDefault();toggleScroll()}if(e.key==='ArrowLeft'){e.preventDefault();$('#exitPlay').click()}if(e.key==='PageDown'){e.preventDefault();$('#playMode').scrollBy({top:innerHeight*.75,behavior:'smooth'})}if(e.key==='PageUp'){e.preventDefault();$('#playMode').scrollBy({top:-innerHeight*.75,behavior:'smooth'})}});
renderList();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
